
CREATE DATABASE MONTSERRAT;

USE MONTSERRAT;

DROP TABLE CUENTA;
DROP TABLE SERVICIO;
DROP TABLE LOCAL;
DROP TABLE PROVEEDOR;
DROP TABLE CLIENTE_SERVICIO;
DROP TABLE DETALLE_SERVICIO;
DROP TABLE TIPO_DOCUMENTO;
--LOGRADO
CREATE TABLE CUENTA (
ID INT NOT NULL PRIMARY KEY,
DESCRIPCION VARCHAR(200) NOT NULL
);
--LOGRADO
CREATE TABLE SERVICIO (
ID INT NOT NULL,
DESCRIPCION VARCHAR(200) NOT NULL,
CUENTA INT NOT NULL,
PRIMARY KEY(ID),
CONSTRAINT FK_CUENTA
FOREIGN KEY (CUENTA) REFERENCES CUENTA(ID)
);
--LOGRADO
CREATE TABLE LOCAL (
SM INT NOT NULL PRIMARY KEY,
NOMBRE VARCHAR(70) NOT NULL,
DIRECCION VARCHAR(255) NOT NULL
);

--LOGRADO
CREATE TABLE PROVEEDOR (
ANALITICO VARCHAR(10) NOT NULL PRIMARY KEY,
RAZON_SOCIAL VARCHAR(150) NOT NULL,
SERVICIO INT NOT NULL,
CONSTRAINT FK_SERVICIO
FOREIGN KEY (SERVICIO) REFERENCES SERVICIO(ID)
);
--LOGRADO (FALTA QUE LISTE LO QUE TIENE LISTO)
CREATE TABLE CLIENTE_SERVICIO (
ID VARCHAR(20) NOT NULL PRIMARY KEY,
PROVEEDOR VARCHAR(10) NOT NULL,
LOCAL INT NOT NULL,
CONSTRAINT FK_LOCAL
FOREIGN KEY (LOCAL) REFERENCES LOCAL(SM),
CONSTRAINT FK_PROVEEDOR
FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDOR(ANALITICO)
);

CREATE TABLE DETALLE_SERVICIO(
ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
LOCAL INT NOT NULL,
PROVEEDOR VARCHAR(10) NOT NULL,
CLIENTE VARCHAR(20) NOT NULL,
PERIODO VARCHAR(20) NOT NULL,
DESDE DATE NOT NULL,
HASTA DATE NOT NULL,
TOTAL INT NOT NULL,
CONSTRAINT FK_LOCAL_DETALLE FOREIGN KEY (LOCAL) REFERENCES LOCAL(SM),
CONSTRAINT FK_PROVEEDOR_DETALLE FOREIGN KEY (PROVEEDOR) REFERENCES PROVEEDOR (ANALITICO),
CONSTRAINT FK_CLIENTE_DETALLE FOREIGN KEY (CLIENTE) REFERENCES CLIENTE_SERVICIO (ID)
);

--META BASICA EN FUNCIONAMIENTO,
--NECESARIO PARA TENER UN CONTROL SOBRE LOS
--SERVICIOS QUE SE INGRESAN EN EL MES

CREATE TABLE TIPO_DOCUMENTO (
ID INT NOT NULL PRIMARY KEY,
TIPO VARCHAR(25) NOT NULL
);
